//
// TBAMatchScoreBreakdown2016.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** See the 2016 FMS API documentation for a description of each value. */

open class TBAMatchScoreBreakdown2016: Codable {

    public var blue: TBAMatchScoreBreakdown2016Alliance?
    public var red: TBAMatchScoreBreakdown2016Alliance?


    
    public init(blue: TBAMatchScoreBreakdown2016Alliance?, red: TBAMatchScoreBreakdown2016Alliance?) {
        self.blue = blue
        self.red = red
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(blue, forKey: "blue")
        try container.encodeIfPresent(red, forKey: "red")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        blue = try container.decodeIfPresent(TBAMatchScoreBreakdown2016Alliance.self, forKey: "blue")
        red = try container.decodeIfPresent(TBAMatchScoreBreakdown2016Alliance.self, forKey: "red")
    }
}

